# A scratch pad
I did some messing around here to get a simple made up example of PCA working at the right level of detail for a talk.  There are some useful things here but it needs cleaning up.

In [49]:
Raw=np.array([[0.42, -1.58, 0.12, -0.18, 1.02, 0.23],
[0.09, -1.61, 0.59, -0.11, 0.69, 0.39],
[0.71, -0.39, -0.89, -0.39, -1.09, 2.01],
[0.82, 0.52, -0.48, 0.02, -0.38, -0.48]])

In [41]:
Raw.T.dot(Raw)

array([[ 1.361 , -0.659 , -0.922 , -0.346 , -0.595 ,  1.1652],
       [-0.659 ,  5.511 , -1.042 ,  0.624 , -2.495 , -2.0248],
       [-0.922 , -1.042 ,  1.385 ,  0.251 ,  1.682 , -1.3008],
       [-0.346 ,  0.624 ,  0.251 ,  0.197 ,  0.158 , -0.8778],
       [-0.595 , -2.495 ,  1.682 ,  0.158 ,  2.849 , -1.5048],
       [ 1.1652, -2.0248, -1.3008, -0.8778, -1.5048,  4.4755]])

In [23]:
from sklearn.decomposition import PCA

In [24]:
pca_tool = PCA(n_components=2)

In [25]:
pc_out = pca_tool.fit_transform(Raw)

In [26]:
pc_out

array([[-1.27972275, -0.14504316],
       [-1.28922204, -0.33916628],
       [ 1.75523918, -1.08002481],
       [ 0.81370561,  1.56423425]])

In [11]:
ordinal=np.array([-3, -2., -1, 1, 2, 3])

In [12]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=ordinal, y=Raw[0], mode="markers"))
fig.add_trace(go.Scatter(x=ordinal, y=Raw[1], mode="markers"))
fig.add_trace(go.Scatter(x=ordinal, y=Raw[2], mode="markers"))
fig.add_trace(go.Scatter(x=ordinal, y=Raw[3], mode="markers"))

In [13]:
A = StandardScaler().fit_transform(Raw)
A

array([[-0.31790016, -0.91548477,  0.50458287, -0.10107257,  1.14039509,
        -0.33753145],
       [-1.48353408, -0.94918359,  1.33670198,  0.37059942,  0.74838428,
        -0.16190533],
       [ 0.7064448 ,  0.42123532, -1.283588  , -1.51608852, -1.36609828,
         1.61630916],
       [ 1.09498944,  1.44343304, -0.55769685,  1.24656167, -0.52268108,
        -1.11687237]])

In [14]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=ordinal, y=A[0], mode="markers",text=["PC1", "PC2"]))
fig.add_trace(go.Scatter(x=ordinal, y=A[1], mode="markers",text=["PC1", "PC2"]))
fig.add_trace(go.Scatter(x=ordinal, y=A[2], mode="markers",text=["PC1", "PC2"]))
fig.add_trace(go.Scatter(x=ordinal, y=A[3], mode="markers",text=["PC1", "PC2"]))

In [50]:
C = np.cov(Raw.T)
print('Covariance matrix \n%s' %C)

Covariance matrix 
[[ 0.10686667  0.30053333 -0.19513333 -0.00313333 -0.23913333  0.0229    ]
 [ 0.30053333  1.0567     -0.51563333  0.0397     -0.77046667 -0.12668333]
 [-0.19513333 -0.51563333  0.42536667  0.04736667  0.57386667 -0.31535   ]
 [-0.00313333  0.0397      0.04736667  0.02936667  0.06586667 -0.17435   ]
 [-0.23913333 -0.77046667  0.57386667  0.06586667  0.94486667 -0.5446    ]
 [ 0.0229     -0.12668333 -0.31535    -0.17435    -0.5446      1.106625  ]]


In [43]:
C=Raw.T.dot(Raw)

In [16]:
without_scaling=np.array([[ 0.76,  0.69,  0.04, -0.20],
[ 0.69,  0.71,  0.04, -0.29],
[ 0.04,  0.04,  1.36,  0.04],
[-0.20, -0.29,  0.04,  0.30]])

In [51]:
eig_vals, eig_vecs = np.linalg.eig(C)

In [54]:
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range(len(eig_vals))]
eig_pairs.sort()
eig_pairs.reverse()
eig_pairs

[(2.3475883903423123,
  array([ 0.17889917,  0.54469984, -0.40707722, -0.04204381, -0.62721092,
          0.33230119])),
 (1.2497845521858881,
  array([-0.11319588, -0.53604903,  0.00189997, -0.13759983, -0.05356904,
          0.82342648])),
 (0.07241872413846522,
  array([ 0.46588541, -0.12050489, -0.7083705 , -0.14647867,  0.49513558,
         -0.00503487])),
 (9.934331162649041e-17,
  array([-0.85914641,  0.11870319, -0.46914044, -0.07005575,  0.14494936,
         -0.04202514])),
 (5.566335804397583e-17,
  array([ 0.4271872 , -0.59894432, -0.03425162,  0.1063727 , -0.56881675,
         -0.35033694])),
 (3.5154098676858706e-18,
  array([-0.14426831, -0.06978912, -0.24746349,  0.94947221,  0.04659844,
          0.09700035]))]

In [55]:
W = np.hstack((eig_pairs[0][1].reshape(6,1), 
               eig_pairs[1][1].reshape(6,1)))
W

array([[ 0.17889917, -0.11319588],
       [ 0.54469984, -0.53604903],
       [-0.40707722,  0.00189997],
       [-0.04204381, -0.13759983],
       [-0.62721092, -0.05356904],
       [ 0.33230119,  0.82342648]])

In [37]:
Raw

array([[ 0.42, -1.58,  0.12, -0.18,  1.02,  0.23],
       [ 0.09, -1.61,  0.59, -0.11,  0.69,  0.39],
       [ 0.71, -0.39, -0.89, -0.39, -1.09,  2.01],
       [ 0.82,  0.52, -0.48,  0.02, -0.38, -0.48]])

In [47]:
Y=Raw.dot(W)
Y

array([[ 1.83547654,  0.43592224],
       [ 1.82622105,  0.43927238],
       [ 0.73384112, -2.5073391 ],
       [-0.717672  , -0.33114711]])

In [53]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=pc_out[:,0], y=pc_out[:,1], mode="markers",text=["PC1", "PC2"]))